#!/bin/bash

cd $FIELDDB_HOME/LexiconWebService
bash switch_to_producti.sh 

forever \
start \
-al $FIELDDB_HOME/logs/fielddblexicon.log \
-ao $FIELDDB_HOME/logs/fielddblexiconout.log \
-ae $FIELDDB_HOME/logs/fielddblexiconerr.log \
lexicon-service.js
