#!/bin/bash

cd $FIELDDB_HOME/LexiconWebService
bash switch_to_producti.sh 

$FIELDDB_HOME/LexiconWebService/node_modules/forever/bin/forever \
start \
-al $FIELDDB_HOME/logs/fielddblexicon.log \
-ao $FIELDDB_HOME/logs/fielddblexiconout.log \
-ae $FIELDDB_HOME/logs/fielddblexiconerr.log \
service.js
